version: '3.8'

services:
  pgdotnet:
    image: postgres:latest
    container_name: pgdotnet
    environment:
      POSTGRES_DB: "bootcamp"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - postgres_data:/var/lib/postgresql/testdb_data
    ports:
      - "5433:5432"
    restart: unless-stopped

  pgadminDotnet:
      image: dpage/pgadmin4:latest
      container_name: pgadminDotnet
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      depends_on:
        - pgdotnet
      restart: unless-stopped

volumes:
  postgres_data: